# Generated by Django 5.1.3 on 2024-11-29 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('idFuncion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('entradas_disponibles', models.PositiveIntegerField(default=28)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='cine.pelicula')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'db_table': 'funcion',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('idEntrada', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.PositiveIntegerField(default=5200)),
                ('vendida', models.BooleanField(default=False)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='cine.funcion')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'entrada',
            },
        ),
    ]
